### PR TITLE
Add Project file to docs

### LINKED ISSUE #46: Needs to set documenter key
The last time `gh-pages` got updated is two years ago...

```julia
┌ Info: Deployment criteria for deploying devbranch build from Travis:
│ - ✔ ENV["TRAVIS_REPO_SLUG"]="JuliaImages/ImageAxes.jl" occurs in repo="github.com/JuliaImages/ImageAxes.jl.git"
│ - ✔ ENV["TRAVIS_PULL_REQUEST"]="false" is "false"
│ - ✔ ENV["TRAVIS_BRANCH"] matches devbranch="master"
│ - ✘ ENV["DOCUMENTER_KEY"] exists
│ - ✔ ENV["TRAVIS_EVENT_TYPE"]="push" is not "cron"
└ Deploying: ✘
```

Perhaps we also need to update `docs` as well (e.g.,  add a `Project.toml`)

### PR DESCRIPTION
**Pull request by timholy**
Closes #46

### CODE REVIEW

**Comment by johnnychen94** [comment]
Is the version bump only to deploy updated documentation?

**Comment by timholy** [comment]
Yes, that's the idea. I guess we could also delete & re-push tags. Would you prefer that?

**Comment by johnnychen94** [comment]
> I guess we could also delete & re-push tags. Would you prefer that?

This looks better to me since we haven't introduced anything new so far.

**Comment by timholy** [comment]
We'll probably lose the nice tag written by TagBot. It will just be `0.6.3` with no further detail. Still worth it?

**Comment by johnnychen94** [comment]
I'd just copy & past 😄 (e.g, from Images.jl to juliaimages.github.io)

Well, tag a new release might be the easiest way without messing things up.

**Review by johnnychen94 — APPROVED** [review]

**Comment by timholy** [comment]
FYI, for coverage nightly will be best due to https://github.com/JuliaLang/julia/pull/34254

**Comment by timholy** [comment]
Thanks!

**Pull request merged**
