### PR TITLE
Disambiguate call to axes() because both Compat and AxisArrays export…

### LINKED ISSUE #25: Functions using axes() fail because Compat exports axes
Since ```axes()``` replaces ```indices()``` on master, ```Compat``` is now exporting ```axes()```, which broke a few functions in ImageAxis, for example : 

```julia
using Images
img = AxisArray(reshape(1:192, (8,8,3)), :x, :y, :time)
imedim(img)
WARNING: both AxisArrays and Compat export "axes"; uses of it in module ImageAxes must be qualified
ERROR: UndefVarError: axes not defined
Stacktrace:
 [1] timedim(::AxisArrays.AxisArray{Int64,3,Base.ReshapedArray{Int64,3,UnitRange{Int64},Tuple{}},Tuple{AxisArrays.Axis{:x,Base.OneTo{Int64}},AxisArrays.Axis{:y,Base.OneTo{Int64}},AxisArrays.Axis{:time,Base.OneTo{Int64}}}}) at /localhome/romain/.julia/v0.6/ImageAxes/src/ImageAxes.jl:136

```

This is on julia 0.6.2.

### PR DESCRIPTION
**Pull request by Cody-G**
… it now.

Fixes #25

### CODE REVIEW

**Review by Evizero — APPROVED** [review]
LGTM. we should probably merge and tag this soon

**Comment by tknopp** [comment]
bump. This makes the package incompatible with julia 0.7.

**Comment by kmsquire** [comment]
The tests are passing on v0.6, failing on nightlies for unrelated reasons, and is untested on v0.7 and v1.0.

I'm going to merge this now, and assume that any additional work/fixes will happen when the package is upgrade to work on v1.0.

If I have time later today, I'll try to take a v0.6 release, then see if I can bump everything v0.7.

**Comment by tknopp** [comment]
Why make a 0.6 Release?

**Comment by kmsquire** [comment]
> Why make a 0.6 Release?

In case there are users stuck on v0.6 that might benefit from this.

**Pull request merged**
